# Necessary in order to adjust maintainability checks
version: "2"
checks:
  similar-code:
    config:
      threshold: 100
  identical-code:
    config:
      threshold: 100
exclude_patterns:
  - "**/test/"
  - "**/androidTest/"
  - "**test"
