package com.example.sharingang.items

import androidx.lifecycle.LiveData

interface ItemRepository {
    /**
     * Returns all items
     */
    suspend fun getAllItems(): List<Item>

    /**
     * Add a new item
     *
     * The item's id must be null.
     *
     * @return id of the item generated by the database
     */
    suspend fun addItem(item: Item): String?

    /**
     * Returns the item with corresponding id or null if it doesn't exist
     */
    suspend fun getItem(id: String): Item?

    /**
     * Returns all items and subscribe to changes.
     *
     * When the database is modified, the new data is provided to the LiveData instance.
     */
    fun getAllItemsLiveData(): LiveData<List<Item>>

    /**
     * Update existing item
     *
     * The item's id cannot be null.
     *
     * @return whether the update succeeded
     */
    suspend fun updateItem(item: Item): Boolean

    /**
     * Delete existing item
     *
     * @return true if the deletion succeeded or there is no item with such id
     */
    suspend fun deleteItem(id: String): Boolean
}