package com.example.sharingang.items

import java.util.Date

import android.os.Parcelable
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import kotlinx.parcelize.Parcelize

/**
 * Item represents an item available for sharing, or for sale.
 */
@Parcelize
data class Item(
    val title: String = "",

    val description: String = "",

    /** URLs of the images */
    val images: List<String> = listOf(),

    val price: Double = 0.0,

    @ServerTimestamp
    val createdAt: Date? = null,

    var category: Int = 0,
    var categoryString : String = "",

    /** ID generated by the database */
    @DocumentId
    val id: String? = null
) : Parcelable
